name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql
          coverage: none
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run tests
        run: composer pest
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql
      - name: Install Laravel dependencies
        run: cp .env.example .env && composer install --prefer-dist --no-progress
      - name: Install Vue.js dependencies
        run: npm install
      - name: Build Vue.js dependencies
        run: npm run build
      - name: Cache Laravel dependencies
        run: |
          php artisan optimize |
          php artisan config:cache |
          php artisan event:cache |
          php artisan route:cache |
          php artisan view:cache
      - name: Archive production artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: public/build
  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: public/build
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
